/* AUTO-GENERATED from the client's "Inventario de Alojamientos" spreadsheet.
   Photos were pulled from the Luxury Atitlán Google Drive folders listed in
   that sheet and now live in /public/img/stays.
   Regenerate with .same/gen_stays.py — do not hand-edit rows. */

import type { Locale } from "./content";

export type StayCategory = "suites" | "apartments";

export type StayPhoto = { src: string; w: number; h: number };

export type StayUnit = {
  slug: string;
  category: StayCategory;
  latin: string;
  name: Record<Locale, string>;
  guests: number;
  bedrooms: number;
  bathrooms: number;
  /** square metres, as reported by the operator */
  size: string;
  beds: Record<Locale, string>;
  highlight: Record<Locale, string>;
  idealFor: Record<Locale, string>;
  airbnb: string;
  photos: StayPhoto[];
  specs: Record<Locale, { k: string; v: string }[]>;
};

export const STAYS: StayUnit[] = [
  {
    slug: "new-york",
    category: "apartments",
    latin: "New York",
    name: { he: "ניו יורק", en: "New York" },
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    size: "48.5",
    beds: { he: "מיטת קווין", en: "Queen bed" },
    highlight: { he: "מרפסת פרטית מול הגן", en: "Private terrace over the garden" },
    idealFor: { he: "מושלם לזוג", en: "Perfect for a couple" },
    airbnb: "https://airbnb.com/h/nysp",
    photos: [
      { src: "/img/stays/new-york/01.jpg", w: 320, h: 180 },
      { src: "/img/stays/new-york/02.jpg", w: 320, h: 180 },
      { src: "/img/stays/new-york/03.jpg", w: 320, h: 180 },
      { src: "/img/stays/new-york/04.jpg", w: 320, h: 180 },
      { src: "/img/stays/new-york/05.jpg", w: 320, h: 427 },
      { src: "/img/stays/new-york/06.jpg", w: 320, h: 427 },
      { src: "/img/stays/new-york/07.jpg", w: 320, h: 427 },
      { src: "/img/stays/new-york/08.jpg", w: 320, h: 427 },
      { src: "/img/stays/new-york/09.jpg", w: 320, h: 427 },
      { src: "/img/stays/new-york/10.jpg", w: 320, h: 427 },
      { src: "/img/stays/new-york/11.jpg", w: 320, h: 427 },
      { src: "/img/stays/new-york/12.jpg", w: 320, h: 427 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "1" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטת קווין" },
      { k: "מיטה נוספת", v: "אפשרית בתוספת" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג אוויר" },
      { k: "מרפסת", v: "מרפסת (ללא נוף לאגם)" },
      { k: "נוף", v: "נוף לגן" },
      { k: "מפלס", v: "קומת קרקע" },
      { k: "מדרגות", v: "כן — מדרגות בירידה ליחידה" },
      { k: "טלוויזיה", v: "מכשיר אחד" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "1" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Queen bed" },
      { k: "Extra bed", v: "Available on request" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning" },
      { k: "Terrace", v: "Terrace (no lake view)" },
      { k: "View", v: "Garden view" },
      { k: "Level", v: "Ground level" },
      { k: "Stairs", v: "Yes — steps down to the unit" },
      { k: "Televisions", v: "1" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "la-villa",
    category: "apartments",
    latin: "La Villa",
    name: { he: "לה וילה", en: "La Villa" },
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    size: "106.9",
    beds: { he: "מיטת קווין + 2 מיטות יחיד", en: "Queen bed + 2 single beds" },
    highlight: { he: "מרפסת מול האגם והגן", en: "Terrace facing lake and garden" },
    idealFor: { he: "מתאים למשפחה", en: "Great for a family" },
    airbnb: "https://airbnb.com/h/lavillasp",
    photos: [
      { src: "/img/stays/la-villa/01.jpg", w: 320, h: 180 },
      { src: "/img/stays/la-villa/02.jpg", w: 320, h: 180 },
      { src: "/img/stays/la-villa/03.jpg", w: 320, h: 180 },
      { src: "/img/stays/la-villa/04.jpg", w: 320, h: 180 },
      { src: "/img/stays/la-villa/05.jpg", w: 320, h: 180 },
      { src: "/img/stays/la-villa/06.jpg", w: 320, h: 427 },
      { src: "/img/stays/la-villa/07.jpg", w: 320, h: 427 },
      { src: "/img/stays/la-villa/08.jpg", w: 320, h: 427 },
      { src: "/img/stays/la-villa/09.jpg", w: 320, h: 427 },
      { src: "/img/stays/la-villa/10.jpg", w: 320, h: 427 },
      { src: "/img/stays/la-villa/11.jpg", w: 320, h: 427 },
      { src: "/img/stays/la-villa/12.jpg", w: 320, h: 427 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "2" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטת קווין + 2 מיטות יחיד" },
      { k: "מיטה נוספת", v: "אפשרית בתוספת" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג בחדר השינה הראשי ובסלון" },
      { k: "מרפסת", v: "מרפסת" },
      { k: "נוף", v: "נוף לאגם ולגן" },
      { k: "מפלס", v: "קומת קרקע" },
      { k: "מדרגות", v: "כן — מדרגות בירידה ליחידה" },
      { k: "טלוויזיה", v: "2 מכשירים" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "2" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Queen bed + 2 single beds" },
      { k: "Extra bed", v: "Available on request" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning in the master bedroom and living room" },
      { k: "Terrace", v: "Terrace" },
      { k: "View", v: "Lake and garden view" },
      { k: "Level", v: "Ground level" },
      { k: "Stairs", v: "Yes — steps down to the unit" },
      { k: "Televisions", v: "2" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "dubai",
    category: "apartments",
    latin: "Dubai",
    name: { he: "דובאי", en: "Dubai" },
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    size: "79.8",
    beds: { he: "מיטת קינג", en: "King bed" },
    highlight: { he: "מרפסת פרטית מול האגם", en: "Private balcony over the lake" },
    idealFor: { he: "מושלם לזוג", en: "Perfect for a couple" },
    airbnb: "https://airbnb.com/h/dubaisp",
    photos: [
      { src: "/img/stays/dubai/01.jpg", w: 320, h: 180 },
      { src: "/img/stays/dubai/02.jpg", w: 320, h: 427 },
      { src: "/img/stays/dubai/03.jpg", w: 320, h: 214 },
      { src: "/img/stays/dubai/04.jpg", w: 320, h: 180 },
      { src: "/img/stays/dubai/05.jpg", w: 320, h: 180 },
      { src: "/img/stays/dubai/06.jpg", w: 320, h: 180 },
      { src: "/img/stays/dubai/07.jpg", w: 320, h: 180 },
      { src: "/img/stays/dubai/08.jpg", w: 320, h: 180 },
      { src: "/img/stays/dubai/09.jpg", w: 320, h: 427 },
      { src: "/img/stays/dubai/10.jpg", w: 320, h: 427 },
      { src: "/img/stays/dubai/11.jpg", w: 320, h: 427 },
      { src: "/img/stays/dubai/12.jpg", w: 320, h: 427 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "1" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטת קינג" },
      { k: "מיטה נוספת", v: "לא" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג אוויר" },
      { k: "מרפסת", v: "מרפסת פרטית עם נוף לאגם" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "קומת קרקע" },
      { k: "מדרגות", v: "כן — מדרגות בירידה ליחידה" },
      { k: "טלוויזיה", v: "מכשיר אחד" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "1" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "King bed" },
      { k: "Extra bed", v: "No" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning" },
      { k: "Terrace", v: "Private balcony with lake view" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Ground level" },
      { k: "Stairs", v: "Yes — steps down to the unit" },
      { k: "Televisions", v: "1" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "tiberias",
    category: "apartments",
    latin: "Tiberias",
    name: { he: "טבריה", en: "Tiberias" },
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    size: "63",
    beds: { he: "מיטה זוגית", en: "Double bed" },
    highlight: { he: "מרפסת מול האגם", en: "Terrace facing the lake" },
    idealFor: { he: "מושלם לזוג", en: "Perfect for a couple" },
    airbnb: "https://airbnb.com/h/tiberiassp",
    photos: [
      { src: "/img/stays/tiberias/01.jpg", w: 320, h: 180 },
      { src: "/img/stays/tiberias/02.jpg", w: 320, h: 180 },
      { src: "/img/stays/tiberias/03.jpg", w: 320, h: 180 },
      { src: "/img/stays/tiberias/04.jpg", w: 320, h: 180 },
      { src: "/img/stays/tiberias/05.jpg", w: 320, h: 180 },
      { src: "/img/stays/tiberias/06.jpg", w: 320, h: 427 },
      { src: "/img/stays/tiberias/07.jpg", w: 320, h: 427 },
      { src: "/img/stays/tiberias/08.jpg", w: 0, h: 0 },
      { src: "/img/stays/tiberias/09.jpg", w: 320, h: 427 },
      { src: "/img/stays/tiberias/10.jpg", w: 320, h: 427 },
      { src: "/img/stays/tiberias/11.jpg", w: 320, h: 427 },
      { src: "/img/stays/tiberias/12.jpg", w: 320, h: 427 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "1" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטה זוגית" },
      { k: "מיטה נוספת", v: "אפשרית בתוספת" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג אוויר" },
      { k: "מרפסת", v: "מרפסת עם נוף לאגם" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "קומת קרקע" },
      { k: "מדרגות", v: "כן — מדרגות בירידה ליחידה" },
      { k: "טלוויזיה", v: "מכשיר אחד" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "1" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Double bed" },
      { k: "Extra bed", v: "Available on request" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning" },
      { k: "Terrace", v: "Terrace with lake view" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Ground level" },
      { k: "Stairs", v: "Yes — steps down to the unit" },
      { k: "Televisions", v: "1" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "venice",
    category: "apartments",
    latin: "Venice",
    name: { he: "ונציה", en: "Venice" },
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    size: "70",
    beds: { he: "מיטה זוגית", en: "Double bed" },
    highlight: { he: "נוף ישיר אל האגם", en: "Direct view onto the lake" },
    idealFor: { he: "מתאים למשפחה", en: "Great for a family" },
    airbnb: "https://airbnb.com/h/veniceluxuryapart",
    photos: [
      { src: "/img/stays/venice/01.jpg", w: 320, h: 213 },
      { src: "/img/stays/venice/02.jpg", w: 320, h: 569 },
      { src: "/img/stays/venice/03.jpg", w: 320, h: 213 },
      { src: "/img/stays/venice/04.jpg", w: 320, h: 213 },
      { src: "/img/stays/venice/05.jpg", w: 320, h: 180 },
      { src: "/img/stays/venice/06.jpg", w: 320, h: 180 },
      { src: "/img/stays/venice/07.jpg", w: 320, h: 180 },
      { src: "/img/stays/venice/08.jpg", w: 320, h: 180 },
      { src: "/img/stays/venice/09.jpg", w: 320, h: 427 },
      { src: "/img/stays/venice/10.jpg", w: 320, h: 427 },
      { src: "/img/stays/venice/11.jpg", w: 320, h: 427 },
      { src: "/img/stays/venice/12.jpg", w: 320, h: 427 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "2" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטה זוגית" },
      { k: "מיטה נוספת", v: "לא" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מאוורר בחדר הראשי, מיזוג בסלון" },
      { k: "מרפסת", v: "נוף ישיר לאגם מהדירה" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "קומת קרקע" },
      { k: "מדרגות", v: "כן — מדרגות בירידה ליחידה" },
      { k: "טלוויזיה", v: "מכשיר אחד" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "2" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Double bed" },
      { k: "Extra bed", v: "No" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Fan in the master bedroom, air conditioning in the living room" },
      { k: "Terrace", v: "Direct lake view from the apartment" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Ground level" },
      { k: "Stairs", v: "Yes — steps down to the unit" },
      { k: "Televisions", v: "1" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "tel-aviv",
    category: "apartments",
    latin: "Tel Aviv",
    name: { he: "תל אביב", en: "Tel Aviv" },
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    size: "70.8",
    beds: { he: "מיטה זוגית", en: "Double bed" },
    highlight: { he: "מרפסת מול האגם", en: "Balcony over the lake" },
    idealFor: { he: "מתאים למשפחה", en: "Great for a family" },
    airbnb: "https://airbnb.com/h/telavivbyluxuryatitlan",
    photos: [
      { src: "/img/stays/tel-aviv/01.jpg", w: 320, h: 427 },
      { src: "/img/stays/tel-aviv/02.jpg", w: 320, h: 427 },
      { src: "/img/stays/tel-aviv/03.jpg", w: 320, h: 427 },
      { src: "/img/stays/tel-aviv/04.jpg", w: 320, h: 427 },
      { src: "/img/stays/tel-aviv/05.jpg", w: 320, h: 427 },
      { src: "/img/stays/tel-aviv/06.jpg", w: 320, h: 427 },
      { src: "/img/stays/tel-aviv/07.jpg", w: 320, h: 427 },
      { src: "/img/stays/tel-aviv/08.jpg", w: 320, h: 427 },
      { src: "/img/stays/tel-aviv/09.jpg", w: 320, h: 427 },
      { src: "/img/stays/tel-aviv/10.jpg", w: 320, h: 427 },
      { src: "/img/stays/tel-aviv/11.jpg", w: 320, h: 427 },
      { src: "/img/stays/tel-aviv/12.jpg", w: 320, h: 427 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "2" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטה זוגית" },
      { k: "מיטה נוספת", v: "אפשרית בתוספת" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג בחדר הראשי ובסלון, מאוורר בכל חדר" },
      { k: "מרפסת", v: "מרפסת עם נוף לאגם" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "קומה 2" },
      { k: "מדרגות", v: "כן — מדרגות בעלייה ליחידה" },
      { k: "טלוויזיה", v: "2 מכשירים" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "2" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Double bed" },
      { k: "Extra bed", v: "Available on request" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning in the master bedroom and living room, fans in every room" },
      { k: "Terrace", v: "Balcony with lake view" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Second floor" },
      { k: "Stairs", v: "Yes — steps up to the unit" },
      { k: "Televisions", v: "2" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "tokyo",
    category: "apartments",
    latin: "Tokyo",
    name: { he: "טוקיו", en: "Tokyo" },
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    size: "51.79",
    beds: { he: "מיטת קווין", en: "Queen bed" },
    highlight: { he: "מרפסת מול האגם", en: "Balcony over the lake" },
    idealFor: { he: "מושלם לזוג", en: "Perfect for a couple" },
    airbnb: "https://airbnb.com/h/tokiobyluxuryatitlan",
    photos: [
      { src: "/img/stays/tokyo/01.jpg", w: 320, h: 427 },
      { src: "/img/stays/tokyo/02.jpg", w: 320, h: 427 },
      { src: "/img/stays/tokyo/03.jpg", w: 320, h: 427 },
      { src: "/img/stays/tokyo/04.jpg", w: 320, h: 427 },
      { src: "/img/stays/tokyo/05.jpg", w: 320, h: 427 },
      { src: "/img/stays/tokyo/06.jpg", w: 320, h: 427 },
      { src: "/img/stays/tokyo/07.jpg", w: 320, h: 427 },
      { src: "/img/stays/tokyo/08.jpg", w: 320, h: 427 },
      { src: "/img/stays/tokyo/09.jpg", w: 320, h: 427 },
      { src: "/img/stays/tokyo/10.jpg", w: 320, h: 427 },
      { src: "/img/stays/tokyo/11.jpg", w: 320, h: 427 },
      { src: "/img/stays/tokyo/12.jpg", w: 320, h: 427 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "1" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטת קווין" },
      { k: "מיטה נוספת", v: "אפשרית בתוספת" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג אוויר ומאוורר" },
      { k: "מרפסת", v: "מרפסת עם נוף לאגם" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "קומה 2" },
      { k: "מדרגות", v: "כן — מדרגות בעלייה ליחידה" },
      { k: "טלוויזיה", v: "מכשיר אחד" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "1" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Queen bed" },
      { k: "Extra bed", v: "Available on request" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning and a fan" },
      { k: "Terrace", v: "Balcony with lake view" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Second floor" },
      { k: "Stairs", v: "Yes — steps up to the unit" },
      { k: "Televisions", v: "1" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "koh-samui",
    category: "apartments",
    latin: "Koh Samui",
    name: { he: "קו סאמוי", en: "Koh Samui" },
    guests: 5,
    bedrooms: 2,
    bathrooms: 1,
    size: "72.49",
    beds: { he: "מיטת קווין, מיטת יחיד ומיטת קומותיים", en: "Queen bed, single bed and a bunk bed" },
    highlight: { he: "מרפסת מול האגם", en: "Balcony over the lake" },
    idealFor: { he: "מתאים למשפחה", en: "Great for a family" },
    airbnb: "https://airbnb.com/h/kosmoibyluxuryatitlan",
    photos: [
      { src: "/img/stays/koh-samui/01.jpg", w: 320, h: 180 },
      { src: "/img/stays/koh-samui/02.jpg", w: 320, h: 427 },
      { src: "/img/stays/koh-samui/03.jpg", w: 320, h: 427 },
      { src: "/img/stays/koh-samui/04.jpg", w: 320, h: 427 },
      { src: "/img/stays/koh-samui/05.jpg", w: 320, h: 427 },
      { src: "/img/stays/koh-samui/06.jpg", w: 320, h: 427 },
      { src: "/img/stays/koh-samui/07.jpg", w: 320, h: 427 },
      { src: "/img/stays/koh-samui/08.jpg", w: 320, h: 427 },
      { src: "/img/stays/koh-samui/09.jpg", w: 320, h: 180 },
      { src: "/img/stays/koh-samui/10.jpg", w: 320, h: 180 },
      { src: "/img/stays/koh-samui/11.jpg", w: 320, h: 180 },
      { src: "/img/stays/koh-samui/12.jpg", w: 320, h: 427 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "2" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטת קווין, מיטת יחיד ומיטת קומותיים" },
      { k: "מיטה נוספת", v: "אפשרית בתוספת" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג בחדר הראשי ובסלון, מאוורר בכל חדר" },
      { k: "מרפסת", v: "מרפסת עם נוף לאגם" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "קומה 2" },
      { k: "מדרגות", v: "כן — מדרגות בעלייה ליחידה" },
      { k: "טלוויזיה", v: "2 מכשירים" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "2" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Queen bed, single bed and a bunk bed" },
      { k: "Extra bed", v: "Available on request" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning in the master bedroom and living room, fans in every room" },
      { k: "Terrace", v: "Balcony with lake view" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Second floor" },
      { k: "Stairs", v: "Yes — steps up to the unit" },
      { k: "Televisions", v: "2" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "bali",
    category: "apartments",
    latin: "Bali",
    name: { he: "באלי", en: "Bali" },
    guests: 6,
    bedrooms: 2,
    bathrooms: 1,
    size: "83.35",
    beds: { he: "מיטה זוגית", en: "Double bed" },
    highlight: { he: "מרפסת מול האגם", en: "Balcony over the lake" },
    idealFor: { he: "מתאים למשפחה", en: "Great for a family" },
    airbnb: "https://airbnb.com/h/balibyluxuryatitlan",
    photos: [
      { src: "/img/stays/bali/01.jpg", w: 320, h: 427 },
      { src: "/img/stays/bali/02.jpg", w: 320, h: 427 },
      { src: "/img/stays/bali/03.jpg", w: 320, h: 427 },
      { src: "/img/stays/bali/04.jpg", w: 320, h: 427 },
      { src: "/img/stays/bali/05.jpg", w: 320, h: 427 },
      { src: "/img/stays/bali/06.jpg", w: 320, h: 427 },
      { src: "/img/stays/bali/07.jpg", w: 320, h: 427 },
      { src: "/img/stays/bali/08.jpg", w: 320, h: 427 },
      { src: "/img/stays/bali/09.jpg", w: 320, h: 427 },
      { src: "/img/stays/bali/10.jpg", w: 320, h: 427 },
      { src: "/img/stays/bali/11.jpg", w: 320, h: 427 },
      { src: "/img/stays/bali/12.jpg", w: 320, h: 427 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "2" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטה זוגית" },
      { k: "מיטה נוספת", v: "אפשרית בתוספת" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג בחדרי השינה ובסלון, מאוורר בכל חדר" },
      { k: "מרפסת", v: "מרפסת עם נוף לאגם" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "קומה 3" },
      { k: "מדרגות", v: "כן — מדרגות בעלייה ליחידה" },
      { k: "טלוויזיה", v: "2 מכשירים" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "2" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Double bed" },
      { k: "Extra bed", v: "Available on request" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning in the bedrooms and living room, fans in every room" },
      { k: "Terrace", v: "Balcony with lake view" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Third floor" },
      { k: "Stairs", v: "Yes — steps up to the unit" },
      { k: "Televisions", v: "2" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "miami",
    category: "apartments",
    latin: "Miami",
    name: { he: "מיאמי", en: "Miami" },
    guests: 7,
    bedrooms: 3,
    bathrooms: 2,
    size: "107.41",
    beds: { he: "מיטת קינג, מיטת יחיד ומיטת קומותיים", en: "King bed, single bed and a bunk bed" },
    highlight: { he: "היחידה הגדולה — 3 חדרים ו-2 מקלחות", en: "The largest unit — 3 bedrooms, 2 bathrooms" },
    idealFor: { he: "מתאים למשפחה", en: "Great for a family" },
    airbnb: "https://airbnb.com/h/miamibyluxuryatitlan",
    photos: [
      { src: "/img/stays/miami/01.jpg", w: 320, h: 214 },
      { src: "/img/stays/miami/02.jpg", w: 320, h: 214 },
      { src: "/img/stays/miami/03.jpg", w: 320, h: 214 },
      { src: "/img/stays/miami/04.jpg", w: 320, h: 214 },
      { src: "/img/stays/miami/05.jpg", w: 320, h: 214 },
      { src: "/img/stays/miami/06.jpg", w: 320, h: 214 },
      { src: "/img/stays/miami/07.jpg", w: 320, h: 214 },
      { src: "/img/stays/miami/08.jpg", w: 320, h: 214 },
      { src: "/img/stays/miami/09.jpg", w: 320, h: 480 },
      { src: "/img/stays/miami/10.jpg", w: 320, h: 214 },
      { src: "/img/stays/miami/11.jpg", w: 320, h: 214 },
      { src: "/img/stays/miami/12.jpg", w: 320, h: 214 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "3" },
      { k: "חדרי רחצה", v: "2" },
      { k: "מיטות", v: "מיטת קינג, מיטת יחיד ומיטת קומותיים" },
      { k: "מיטה נוספת", v: "אפשרית בתוספת" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג בחדר הראשי, בחדר הילדים ובסלון, מאוורר בכל חדר" },
      { k: "מרפסת", v: "מרפסת עם נוף לאגם" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "קומה 3" },
      { k: "מדרגות", v: "כן — מדרגות בעלייה ליחידה" },
      { k: "טלוויזיה", v: "3 מכשירים" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "3" },
      { k: "Bathrooms", v: "2" },
      { k: "Beds", v: "King bed, single bed and a bunk bed" },
      { k: "Extra bed", v: "Available on request" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning in the master bedroom, children's room and living room, fans in every room" },
      { k: "Terrace", v: "Balcony with lake view" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Third floor" },
      { k: "Stairs", v: "Yes — steps up to the unit" },
      { k: "Televisions", v: "3" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "san-pedro",
    category: "apartments",
    latin: "San Pedro",
    name: { he: "סן פדרו", en: "San Pedro" },
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    size: "60.79",
    beds: { he: "מיטה זוגית", en: "Double bed" },
    highlight: { he: "מרפסת מול האגם", en: "Balcony over the lake" },
    idealFor: { he: "מתאים למשפחה", en: "Great for a family" },
    airbnb: "https://airbnb.com/h/sanpedrosuite0",
    photos: [
      { src: "/img/stays/san-pedro/01.jpg", w: 320, h: 180 },
      { src: "/img/stays/san-pedro/02.jpg", w: 320, h: 188 },
      { src: "/img/stays/san-pedro/03.jpg", w: 320, h: 180 },
      { src: "/img/stays/san-pedro/04.jpg", w: 320, h: 180 },
      { src: "/img/stays/san-pedro/05.jpg", w: 320, h: 180 },
      { src: "/img/stays/san-pedro/06.jpg", w: 320, h: 180 },
      { src: "/img/stays/san-pedro/07.jpg", w: 320, h: 180 },
      { src: "/img/stays/san-pedro/08.jpg", w: 320, h: 180 },
      { src: "/img/stays/san-pedro/09.jpg", w: 320, h: 180 },
      { src: "/img/stays/san-pedro/10.jpg", w: 320, h: 180 },
      { src: "/img/stays/san-pedro/11.jpg", w: 320, h: 180 },
      { src: "/img/stays/san-pedro/12.jpg", w: 320, h: 180 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "2" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטה זוגית" },
      { k: "מיטה נוספת", v: "אפשרית בתוספת" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג בסלון, מאוורר בחדר הראשי" },
      { k: "מרפסת", v: "מרפסת עם נוף לאגם" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "קומת קרקע" },
      { k: "מדרגות", v: "כן — מדרגות בירידה ליחידה" },
      { k: "טלוויזיה", v: "מכשיר אחד" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "2" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Double bed" },
      { k: "Extra bed", v: "Available on request" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning in the living room, fan in the master bedroom" },
      { k: "Terrace", v: "Balcony with lake view" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Ground level" },
      { k: "Stairs", v: "Yes — steps down to the unit" },
      { k: "Televisions", v: "1" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "suite-1",
    category: "suites",
    latin: "Suite 1",
    name: { he: "סוויטה 1", en: "Suite 1" },
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    size: "50.95",
    beds: { he: "מיטת קווין", en: "Queen bed" },
    highlight: { he: "מרפסת מול הגן", en: "Terrace over the garden" },
    idealFor: { he: "מתאים למשפחה", en: "Great for a family" },
    airbnb: "https://airbnb.com/h/suite1byluxuryatitlan",
    photos: [
      { src: "/img/stays/suite-1/01.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-1/02.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-1/03.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-1/04.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-1/05.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-1/06.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-1/07.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-1/08.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-1/09.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-1/10.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-1/11.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-1/12.jpg", w: 320, h: 213 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "2" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטת קווין" },
      { k: "מיטה נוספת", v: "אפשרית בתוספת" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג בסלון, מאוורר בחדרי השינה" },
      { k: "מרפסת", v: "מרפסת (ללא נוף לאגם)" },
      { k: "נוף", v: "נוף לגן" },
      { k: "מפלס", v: "קומת קרקע" },
      { k: "מדרגות", v: "כן — מדרגות בעלייה ליחידה" },
      { k: "טלוויזיה", v: "מכשיר אחד" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "2" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Queen bed" },
      { k: "Extra bed", v: "Available on request" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning in the living room, fans in the bedrooms" },
      { k: "Terrace", v: "Terrace (no lake view)" },
      { k: "View", v: "Garden view" },
      { k: "Level", v: "Ground level" },
      { k: "Stairs", v: "Yes — steps up to the unit" },
      { k: "Televisions", v: "1" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "suite-2",
    category: "suites",
    latin: "Suite 2",
    name: { he: "סוויטה 2", en: "Suite 2" },
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    size: "45.92",
    beds: { he: "מיטת קווין", en: "Queen bed" },
    highlight: { he: "מרפסת פרטית מול האגם", en: "Private balcony over the lake" },
    idealFor: { he: "מושלם לזוג", en: "Perfect for a couple" },
    airbnb: "https://airbnb.com/h/suite2byluxuryatitlan",
    photos: [
      { src: "/img/stays/suite-2/01.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-2/02.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-2/03.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-2/04.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-2/05.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-2/06.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-2/07.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-2/08.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-2/09.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-2/10.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-2/11.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-2/12.jpg", w: 320, h: 427 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "1" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטת קווין" },
      { k: "מיטה נוספת", v: "אפשרית בתוספת" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג אוויר" },
      { k: "מרפסת", v: "מרפסת עם נוף לאגם" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "מתחם 2" },
      { k: "מדרגות", v: "כן — מדרגות בעלייה ליחידה" },
      { k: "טלוויזיה", v: "מכשיר אחד" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "1" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Queen bed" },
      { k: "Extra bed", v: "Available on request" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning" },
      { k: "Terrace", v: "Balcony with lake view" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Plot 2" },
      { k: "Stairs", v: "Yes — steps up to the unit" },
      { k: "Televisions", v: "1" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "suite-3",
    category: "suites",
    latin: "Suite 3",
    name: { he: "סוויטה 3", en: "Suite 3" },
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    size: "50.95",
    beds: { he: "מיטת קווין", en: "Queen bed" },
    highlight: { he: "מרפסת פרטית מול האגם", en: "Private balcony over the lake" },
    idealFor: { he: "מתאים למשפחה", en: "Great for a family" },
    airbnb: "https://airbnb.com/h/suite3byluxuryatitlan",
    photos: [
      { src: "/img/stays/suite-3/01.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-3/02.jpg", w: 320, h: 427 },
      { src: "/img/stays/suite-3/03.jpg", w: 320, h: 427 },
      { src: "/img/stays/suite-3/04.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-3/05.jpg", w: 320, h: 427 },
      { src: "/img/stays/suite-3/06.jpg", w: 320, h: 287 },
      { src: "/img/stays/suite-3/07.jpg", w: 320, h: 427 },
      { src: "/img/stays/suite-3/08.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-3/09.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-3/10.jpg", w: 320, h: 427 },
      { src: "/img/stays/suite-3/11.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-3/12.jpg", w: 320, h: 427 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "2" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטת קווין" },
      { k: "מיטה נוספת", v: "אפשרית בתוספת" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג בסלון, מאוורר בחדרי השינה" },
      { k: "מרפסת", v: "מרפסת עם נוף לאגם" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "מתחם 2" },
      { k: "מדרגות", v: "כן — מדרגות בעלייה ליחידה" },
      { k: "טלוויזיה", v: "מכשיר אחד" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "2" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Queen bed" },
      { k: "Extra bed", v: "Available on request" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning in the living room, fans in the bedrooms" },
      { k: "Terrace", v: "Balcony with lake view" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Plot 2" },
      { k: "Stairs", v: "Yes — steps up to the unit" },
      { k: "Televisions", v: "1" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "suite-4",
    category: "suites",
    latin: "Suite 4",
    name: { he: "סוויטה 4", en: "Suite 4" },
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    size: "48.19",
    beds: { he: "מיטת קווין", en: "Queen bed" },
    highlight: { he: "מרפסת מול האגם", en: "Balcony over the lake" },
    idealFor: { he: "מושלם לזוג", en: "Perfect for a couple" },
    airbnb: "https://airbnb.com/h/suite4byluxuryatitlan",
    photos: [
      { src: "/img/stays/suite-4/01.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-4/02.jpg", w: 320, h: 456 },
      { src: "/img/stays/suite-4/03.jpg", w: 320, h: 427 },
      { src: "/img/stays/suite-4/04.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-4/05.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-4/06.jpg", w: 320, h: 427 },
      { src: "/img/stays/suite-4/07.jpg", w: 320, h: 427 },
      { src: "/img/stays/suite-4/08.jpg", w: 320, h: 427 },
      { src: "/img/stays/suite-4/09.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-4/10.jpg", w: 320, h: 427 },
      { src: "/img/stays/suite-4/11.jpg", w: 320, h: 152 },
      { src: "/img/stays/suite-4/12.jpg", w: 320, h: 158 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "1" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטת קווין" },
      { k: "מיטה נוספת", v: "לא" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג אוויר" },
      { k: "מרפסת", v: "מרפסת משותפת עם נוף לאגם" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "מתחם 2" },
      { k: "מדרגות", v: "כן — מדרגות בעלייה ליחידה" },
      { k: "טלוויזיה", v: "מכשיר אחד" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "1" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Queen bed" },
      { k: "Extra bed", v: "No" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning" },
      { k: "Terrace", v: "Shared balcony with lake view" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Plot 2" },
      { k: "Stairs", v: "Yes — steps up to the unit" },
      { k: "Televisions", v: "1" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "suite-5",
    category: "suites",
    latin: "Suite 5",
    name: { he: "סוויטה 5", en: "Suite 5" },
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    size: "50.95",
    beds: { he: "מיטת קווין", en: "Queen bed" },
    highlight: { he: "מרפסת מול האגם", en: "Balcony over the lake" },
    idealFor: { he: "מתאים למשפחה", en: "Great for a family" },
    airbnb: "https://airbnb.com/h/suite5byluxuryatitlan",
    photos: [
      { src: "/img/stays/suite-5/01.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-5/02.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-5/03.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-5/04.jpg", w: 320, h: 427 },
      { src: "/img/stays/suite-5/05.jpg", w: 320, h: 400 },
      { src: "/img/stays/suite-5/06.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-5/07.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-5/08.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-5/09.jpg", w: 320, h: 427 },
      { src: "/img/stays/suite-5/10.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-5/11.jpg", w: 320, h: 427 },
      { src: "/img/stays/suite-5/12.jpg", w: 320, h: 213 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "2" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטת קווין" },
      { k: "מיטה נוספת", v: "אפשרית בתוספת" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג בסלון, מאוורר בחדרי השינה" },
      { k: "מרפסת", v: "מרפסת משותפת עם נוף לאגם" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "מתחם 2" },
      { k: "מדרגות", v: "כן — מדרגות בעלייה ליחידה" },
      { k: "טלוויזיה", v: "מכשיר אחד" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "2" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Queen bed" },
      { k: "Extra bed", v: "Available on request" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning in the living room, fans in the bedrooms" },
      { k: "Terrace", v: "Shared balcony with lake view" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Plot 2" },
      { k: "Stairs", v: "Yes — steps up to the unit" },
      { k: "Televisions", v: "1" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "suite-6",
    category: "suites",
    latin: "Suite 6",
    name: { he: "סוויטה 6", en: "Suite 6" },
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    size: "45.92",
    beds: { he: "מיטת קווין", en: "Queen bed" },
    highlight: { he: "מרפסת מול האגם", en: "Balcony over the lake" },
    idealFor: { he: "מושלם לזוג", en: "Perfect for a couple" },
    airbnb: "https://airbnb.com/h/suite6byluxuryatitlan",
    photos: [
      { src: "/img/stays/suite-6/01.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-6/02.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-6/03.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-6/04.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-6/05.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-6/06.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-6/07.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-6/08.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-6/09.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-6/10.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-6/11.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-6/12.jpg", w: 320, h: 213 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "1" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטת קווין" },
      { k: "מיטה נוספת", v: "לא" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג אוויר" },
      { k: "מרפסת", v: "מרפסת משותפת עם נוף לאגם" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "מתחם 3" },
      { k: "מדרגות", v: "כן — מדרגות בעלייה ליחידה" },
      { k: "טלוויזיה", v: "מכשיר אחד" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "1" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Queen bed" },
      { k: "Extra bed", v: "No" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning" },
      { k: "Terrace", v: "Shared balcony with lake view" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Plot 3" },
      { k: "Stairs", v: "Yes — steps up to the unit" },
      { k: "Televisions", v: "1" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "suite-7",
    category: "suites",
    latin: "Suite 7",
    name: { he: "סוויטה 7", en: "Suite 7" },
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    size: "50.95",
    beds: { he: "מיטת קווין + 2 מיטות יחיד", en: "Queen bed + 2 single beds" },
    highlight: { he: "מרפסת מול האגם", en: "Balcony over the lake" },
    idealFor: { he: "מתאים למשפחה", en: "Great for a family" },
    airbnb: "https://airbnb.com/h/suite7byluxuryatitlan",
    photos: [
      { src: "/img/stays/suite-7/01.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-7/02.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-7/03.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-7/04.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-7/05.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-7/06.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-7/07.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-7/08.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-7/09.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-7/10.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-7/11.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-7/12.jpg", w: 320, h: 213 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "2" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטת קווין + 2 מיטות יחיד" },
      { k: "מיטה נוספת", v: "לא" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג בסלון, מאוורר בחדרי השינה" },
      { k: "מרפסת", v: "מרפסת משותפת עם נוף לאגם" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "מתחם 3" },
      { k: "מדרגות", v: "כן — מדרגות בעלייה ליחידה" },
      { k: "טלוויזיה", v: "מכשיר אחד" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "2" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Queen bed + 2 single beds" },
      { k: "Extra bed", v: "No" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning in the living room, fans in the bedrooms" },
      { k: "Terrace", v: "Shared balcony with lake view" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Plot 3" },
      { k: "Stairs", v: "Yes — steps up to the unit" },
      { k: "Televisions", v: "1" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "suite-8",
    category: "suites",
    latin: "Suite 8",
    name: { he: "סוויטה 8", en: "Suite 8" },
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    size: "32.29",
    beds: { he: "מיטת קווין", en: "Queen bed" },
    highlight: { he: "קומפקטית, עם נוף לאגם", en: "Compact, with a lake view" },
    idealFor: { he: "מושלם לזוג", en: "Perfect for a couple" },
    airbnb: "https://airbnb.com/h/suite8byluxuryatitlan",
    photos: [
      { src: "/img/stays/suite-8/01.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-8/02.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-8/03.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-8/04.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-8/05.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-8/06.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-8/07.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-8/08.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-8/09.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-8/10.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-8/11.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-8/12.jpg", w: 320, h: 180 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "1" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטת קווין" },
      { k: "מיטה נוספת", v: "לא" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג אוויר" },
      { k: "מרפסת", v: "מרפסת משותפת עם נוף לאגם" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "מתחם 4" },
      { k: "מדרגות", v: "כן — מדרגות בעלייה ליחידה" },
      { k: "טלוויזיה", v: "מכשיר אחד" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "1" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Queen bed" },
      { k: "Extra bed", v: "No" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning" },
      { k: "Terrace", v: "Shared balcony with lake view" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Plot 4" },
      { k: "Stairs", v: "Yes — steps up to the unit" },
      { k: "Televisions", v: "1" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "suite-9",
    category: "suites",
    latin: "Suite 9",
    name: { he: "סוויטה 9", en: "Suite 9" },
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    size: "32.29",
    beds: { he: "מיטת קווין", en: "Queen bed" },
    highlight: { he: "קומפקטית, עם נוף לאגם", en: "Compact, with a lake view" },
    idealFor: { he: "מושלם לזוג", en: "Perfect for a couple" },
    airbnb: "https://airbnb.com/h/suite9byluxuryatitlan",
    photos: [
      { src: "/img/stays/suite-9/01.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-9/02.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-9/03.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-9/04.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-9/05.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-9/06.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-9/07.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-9/08.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-9/09.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-9/10.jpg", w: 320, h: 213 },
      { src: "/img/stays/suite-9/11.jpg", w: 320, h: 213 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "1" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטת קווין" },
      { k: "מיטה נוספת", v: "לא" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג אוויר" },
      { k: "מרפסת", v: "מרפסת משותפת עם נוף לאגם" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "מתחם 4" },
      { k: "מדרגות", v: "כן — מדרגות בעלייה ליחידה" },
      { k: "טלוויזיה", v: "מכשיר אחד" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "1" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Queen bed" },
      { k: "Extra bed", v: "No" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning" },
      { k: "Terrace", v: "Shared balcony with lake view" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Plot 4" },
      { k: "Stairs", v: "Yes — steps up to the unit" },
      { k: "Televisions", v: "1" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
  {
    slug: "suite-10",
    category: "suites",
    latin: "Suite 10",
    name: { he: "סוויטה 10", en: "Suite 10" },
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    size: "69.79",
    beds: { he: "מיטת קווין + 2 מיטות יחיד", en: "Queen bed + 2 single beds" },
    highlight: { he: "מרפסת פרטית מול האגם", en: "Private balcony over the lake" },
    idealFor: { he: "מתאים למשפחה", en: "Great for a family" },
    airbnb: "https://airbnb.com/h/suite10byluxuryatitlan",
    photos: [
      { src: "/img/stays/suite-10/01.jpg", w: 320, h: 180 },
      { src: "/img/stays/suite-10/02.jpg", w: 320, h: 180 },
      { src: "/img/stays/suite-10/03.jpg", w: 320, h: 180 },
      { src: "/img/stays/suite-10/04.jpg", w: 320, h: 180 },
      { src: "/img/stays/suite-10/05.jpg", w: 320, h: 180 },
      { src: "/img/stays/suite-10/06.jpg", w: 320, h: 180 },
      { src: "/img/stays/suite-10/07.jpg", w: 320, h: 180 },
      { src: "/img/stays/suite-10/08.jpg", w: 320, h: 180 },
      { src: "/img/stays/suite-10/09.jpg", w: 320, h: 180 },
      { src: "/img/stays/suite-10/10.jpg", w: 320, h: 180 },
      { src: "/img/stays/suite-10/11.jpg", w: 320, h: 180 },
      { src: "/img/stays/suite-10/12.jpg", w: 320, h: 180 },
    ],
    specs: {
      he: [
      { k: "חדרי שינה", v: "2" },
      { k: "חדרי רחצה", v: "1" },
      { k: "מיטות", v: "מיטת קווין + 2 מיטות יחיד" },
      { k: "מיטה נוספת", v: "אפשרית בתוספת" },
      { k: "עריסה לתינוק", v: "זמינה" },
      { k: "מטבח", v: "מטבחון מאובזר" },
      { k: "מיזוג", v: "מיזוג בסלון, מאוורר בחדרי השינה" },
      { k: "מרפסת", v: "מרפסת פרטית עם נוף לאגם" },
      { k: "נוף", v: "נוף לאגם" },
      { k: "מפלס", v: "מתחם 5" },
      { k: "מדרגות", v: "כן — מדרגות בעלייה ליחידה" },
      { k: "טלוויזיה", v: "2 מכשירים" },
      { k: "אינטרנט אלחוטי", v: "כן" },
      { k: "מים חמים", v: "כן" },
      ],
      en: [
      { k: "Bedrooms", v: "2" },
      { k: "Bathrooms", v: "1" },
      { k: "Beds", v: "Queen bed + 2 single beds" },
      { k: "Extra bed", v: "Available on request" },
      { k: "Baby crib", v: "Available" },
      { k: "Kitchen", v: "Equipped kitchenette" },
      { k: "Climate", v: "Air conditioning in the living room, fans in the bedrooms" },
      { k: "Terrace", v: "Private balcony with lake view" },
      { k: "View", v: "Lake view" },
      { k: "Level", v: "Plot 5" },
      { k: "Stairs", v: "Yes — steps up to the unit" },
      { k: "Televisions", v: "2" },
      { k: "Wi-Fi", v: "Yes" },
      { k: "Hot water", v: "Yes" },
      ],
    },
  },
];

export const COMPLEX: Record<
  StayCategory,
  {
    slug: StayCategory;
    label: Record<Locale, string>;
    tagline: Record<Locale, string>;
    blurb: Record<Locale, string>;
    body: Record<Locale, string>;
    cta: Record<Locale, string>;
    /** image used for the big banner */
    hero: string;
    facilities: Record<Locale, string[]>;
  }
> = {
  suites: {
    slug: "suites",
    hero: "/img/stays/suite-10/01.jpg",
    label: { he: "סוויטות", en: "Suites" },
    tagline: { he: "חמישים מטר מהמים", en: "Fifty metres from the water" },
    blurb: {
      he: "עשר סוויטות על מדרון הגבעה, רובן עם מרפסת אל האגם.",
      en: "Ten suites on the hillside, most with a balcony over the lake.",
    },
    body: {
      he: "מרחק צעדים מהאגם. סוויטות שקטות, מוקפות ירק, עם נוף שמלווה אתכם מהבוקר ועד השקיעה — מקום להתאושש בו אחרי יום של הליכה.",
      en: "A few steps from the lake. Quiet suites wrapped in green, with a view that stays with you from morning to sunset — somewhere to recover after a day on the trails.",
    },
    cta: { he: "לכל הסוויטות", en: "View all suites" },
    facilities: {
      he: ["בריכה משותפת", "ג׳קוזי", "סאונה", "מטבחון מאובזר", "אינטרנט אלחוטי", "מים חמים"],
      en: ["Shared pool", "Jacuzzi", "Sauna", "Equipped kitchenette", "Wi-Fi", "Hot water"],
    },
  },
  apartments: {
    slug: "apartments",
    hero: "/img/stays/dubai/01.jpg",
    label: { he: "דירות", en: "Apartments" },
    tagline: { he: "ממש על שפת האגם", en: "Right on the lake shore" },
    blurb: {
      he: "אחת עשרה דירות מול המים, עם גישה ישירה לאגם.",
      en: "Eleven apartments facing the water, with direct access to the lake.",
    },
    body: {
      he: "פינה יפה מול האגם, שבה מתעוררים לנוף ויורדים ישר למים. מקום להירגע בו, לנשום את ההרים, ולהישאר עוד יום.",
      en: "A beautiful corner facing the lake, where you wake up to the view and walk straight down to the water. Somewhere to slow down, breathe the mountains in, and stay another day.",
    },
    cta: { he: "לכל הדירות", en: "View all apartments" },
    facilities: {
      he: ["בריכה משותפת", "ג׳קוזי", "סאונה", "מטבחון מאובזר", "אינטרנט אלחוטי", "מים חמים"],
      en: ["Shared pool", "Jacuzzi", "Sauna", "Equipped kitchenette", "Wi-Fi", "Hot water"],
    },
  },
};

export const STAY_LABELS: Record<
  Locale,
  {
    guests: string;
    beds: string;
    size: string;
    sizeUnit: string;
    bedrooms: string;
    details: string;
    book: string;
    bookAirbnb: string;
    gallery: string;
    photos: string;
    allUnits: string;
    backToStay: string;
    specs: string;
    facilities: string;
    ask: string;
    units: string;
    others: string;
    chooseTitle: string;
    chooseLead: string;
  }
> = {
  he: {
    guests: "אורחים",
    beds: "מיטות",
    size: "גודל",
    sizeUnit: "מ״ר",
    bedrooms: "חדרי שינה",
    details: "לפרטים",
    book: "להזמנה",
    bookAirbnb: "להזמנה ב-Airbnb",
    gallery: "גלריה",
    photos: "תמונות",
    allUnits: "לכל היחידות",
    backToStay: "חזרה לעמוד הלינה",
    specs: "פרטי היחידה",
    facilities: "במתחם",
    ask: "שאלה על היחידה",
    units: "יחידות",
    others: "יחידות נוספות",
    chooseTitle: "איפה תרצו לישון",
    chooseLead: "שני מתחמים על שפת האגם, במרחק הליכה קצר מבית חב״ד. בחרו את הסגנון — ואז את היחידה.",
  },
  en: {
    guests: "Guests",
    beds: "Beds",
    size: "Size",
    sizeUnit: "m²",
    bedrooms: "Bedrooms",
    details: "Details",
    book: "Book",
    bookAirbnb: "Book on Airbnb",
    gallery: "Gallery",
    photos: "photos",
    allUnits: "All units",
    backToStay: "Back to accommodation",
    specs: "Unit details",
    facilities: "In the complex",
    ask: "Ask about this unit",
    units: "units",
    others: "Other units",
    chooseTitle: "Where would you like to sleep",
    chooseLead: "Two complexes on the lake shore, a short walk from the Chabad House. Choose the style — then the unit.",
  },
};

export const unitsIn = (c: StayCategory) =>
  STAYS.filter((u) => u.category === c);

export const findUnit = (c: string, slug: string) =>
  STAYS.find((u) => u.category === c && u.slug === slug);
